Fixed the build failure on Xcode 12.5
Ahmed-Ali/Cucumberish pull request #140
Opened 2021-04-27 12:37 UTC by duyquang91

fix: Fixed build failure on Xcode 12.5

2021-05-12 02:35 UTC, Jackychnag325 commented
When will this fix be merged and released?

2021-05-12 16:35 UTC, 4PixelsDev requested changes

2021-05-12 16:35 UTC, 4PixelsDev commented on CucumberishLibraryTest/CucumberishFeatureDefinition/CucumberFeatureSteps.m
> +                    CCIAssert(![step[@"result"][@"duration"] isEqual:@0], @"The duration wasn't set to the result of the step");
I don't think this is the correct fix, because the check was is the duration > 0, not is the duration != 0.
Your fix would return true even if the duration is a negative value.

To keep the original logic I suggest this solution:
```
[step[@"result"][@"duration"] doubleValue] > 0
```

2021-05-12 16:42 UTC, 4PixelsDev approved these changes

2021-05-26 20:12 UTC, renanvs commented
> When will this fix be merged and released?

I waiting for this release too. Do You have some news about merge?

2021-05-27 07:21 UTC, tobi3358 commented
Waiting for This merge any news

2021-05-28 17:05 UTC, duyquang91 commented on CucumberishLibraryTest/CucumberishFeatureDefinition/CucumberFeatureSteps.m
> +                    CCIAssert(![step[@"result"][@"duration"] isEqual:@0], @"The duration wasn't set to the result of the step");
Sorry for my late response. I updated the PR base on your request, feel free to review again. Thanks!

2021-06-02 13:02 UTC, 4PixelsDev commented on CucumberishLibraryTest/CucumberishFeatureDefinition/CucumberFeatureSteps.m
> +                    CCIAssert(![step[@"result"][@"duration"] isEqual:@0], @"The duration wasn't set to the result of the step");
LGTM :)

2021-06-03 04:15 UTC, depoon commented
I need this as well... am messaging the author ... got him on DM

2021-06-03 18:44 UTC, merged

2021-06-29 05:05 UTC, Jackychnag325 commented
Will you release a new tag version for this fix?

2021-06-29 12:21 UTC, sdanny commented
Does someone has same issue with this fix? Every time I try to restart some finished test case from the Test Navigator it starts under feature named `XCTestCase` rather than original one? Then it just fails this test case even if previously it succeeded.